Appointment screen
LCIS-codepath/Appointsy pull request #19
Opened 2021-04-19 09:12 UTC by eisajanyan

Closes #5

2021-04-19 15:59 UTC, EChilin5 requested changes
Fix the issue with activity_register.xml. Everything else is fine.

2021-04-19 15:59 UTC, EChilin5 commented on app/src/main/res/layout/activity_register.xml
> -        android:id="@+id/tiName"
Remove the id with tiName. It should resolve the code conflict.

2021-04-21 03:49 UTC, EChilin5 approved these changes

2021-04-21 03:53 UTC, DSantanax approved these changes

2021-04-21 03:53 UTC, merged